### ISSUE TITLE
nexus 5，调用前置摄像头，图像被拉伸。

### ISSUE THREAD

**Issue by KennethYo** [Skykai521/StickerCamera#21]
Nexus 5，Android 6.0
后置摄像头，图片正常，点击切换摄像头，切换为前置摄像头，显示图像明显被拉伸，但是存储的图片没有拉伸。
这里我刚刚截获了 log 日志。

``` java
java.lang.RuntimeException: setParameters failed
at android.hardware.Camera.native_setParameters(Native Method)
at android.hardware.Camera.setParameters(Camera.java:1878)
at com.stickercamera.app.camera.ui.CameraActivity.initCamera(CameraActivity.java:486)
at com.stickercamera.app.camera.ui.CameraActivity.setUpCamera(CameraActivity.java:824)
at com.stickercamera.app.camera.ui.CameraActivity.switchCamera(CameraActivity.java:803)
at com.stickercamera.app.camera.ui.CameraActivity.lambda$initEvent$3(CameraActivity.java:198)
at com.stickercamera.app.camera.ui.CameraActivity.access$lambda$3(CameraActivity.java)
at com.stickercamera.app.camera.ui.CameraActivity$$Lambda$6.onClick(Unknown Source)
at android.view.View.performClick(View.java:5198)
at android.view.View$PerformClick.run(View.java:21147)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by yimiIO** [comment]
解决了么
