### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by xingag** [Skykai521/StickerCamera#8]
错误日志如下：
08-13 10:22:16.197  29841-29858/com.github.skykai.stickercamera E/System﹕ Uncaught exception thrown by finalizer
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ Throwing OutOfMemoryError "Failed to allocate a 28 byte allocation with 0 free bytes and 3GB until OOM" (recursive case)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ "main" prio=5 tid=1 Runnable
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ | group="main" sCount=0 dsCount=0 obj=0x86479f88 self=0xb4e07800
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ | sysTid=29841 nice=-11 cgrp=apps sched=0/0 handle=0xb6f04ec8
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ | state=R schedstat=( 1037871833 557194121 2071 ) utm=87 stm=16 core=1 HZ=100
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ | stack=0xbe1bf000-0xbe1c1000 stackSize=8MB
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ | held mutexes= "mutator lock"(shared held)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.graphics.drawable.Drawable.getBounds(Drawable.java:259)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.graphics.drawable.ColorDrawable.getOutline(ColorDrawable.java:216)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewOutlineProvider$1.getOutline(ViewOutlineProvider.java:38)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.View.rebuildOutline(View.java:12104)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.View.onAttachedToWindow(View.java:13995)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewGroup.onAttachedToWindow(ViewGroup.java:4147)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.View.dispatchAttachedToWindow(View.java:14467)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3001)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3009)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3009)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3009)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ ... repeated 1 times
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1449)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6643)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.Choreographer.doCallbacks(Choreographer.java:590)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.Choreographer.doFrame(Choreographer.java:560)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.os.Handler.handleCallback(Handler.java:739)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.os.Handler.dispatchMessage(Handler.java:95)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.os.Looper.loop(Looper.java:145)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at android.app.ActivityThread.main(ActivityThread.java:5942)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at java.lang.reflect.Method.invoke!(Native method)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at java.lang.reflect.Method.invoke(Method.java:372)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
08-13 10:22:16.197  29841-29841/com.github.skykai.stickercamera E/art﹕ [ 08-13 10:22:16.207   943: 1773 D/WifiService ]
    startScan by pid=29780, uid=10324

**Comment by Skykai521** [comment]
是必现OOM吗?尝试在manifest 的 application 标签里 加上 android:largeHeap="true"

**Comment by xingag** [comment]
刚才跑了几篇，很容易出现，我是三星note3
